import "dotenv/config";
import { CRON_JOBS, type CronJob } from "../src/lib/cron-schedule";

/**
 * Print the crontab block for this app, rendered from CRON_JOBS.
 *
 * Written after finding that `sms-queue` had never been added to the server's
 * crontab. Every message handed in outside the 8am-8pm SMS delivery window had
 * been queued and left there, for months, because the schedule lived only in a
 * crontab nobody could diff against anything. Nine of the thirteen jobs were
 * in the same position: running, but by nothing the repository knew about.
 *
 * So the schedule is in `src/lib/cron-schedule.ts` and this renders it. A job
 * added to that object appears here; one that is here and not on the server is
 * a one-line diff rather than an archaeology exercise.
 *
 * Usage:
 *   pnpm exec tsx scripts/print-crontab.ts            # review the block
 *   pnpm exec tsx scripts/print-crontab.ts --install   # install it
 *
 * --install REPLACES ONLY THE MARKED BLOCK and leaves every other line in the
 * crontab untouched — backups, the watchdog, anything else on the box. It
 * writes a timestamped copy of the existing crontab to the home directory
 * first, so the previous schedule is always recoverable.
 */

const BEGIN = "# >>> flockinsight crons >>>";
const END = "# <<< flockinsight crons <<<";

function baseUrl(): string {
  const url = process.env.BETTER_AUTH_URL || process.env.NEXT_PUBLIC_APP_URL;
  if (!url) {
    throw new Error(
      "BETTER_AUTH_URL is not set, so the cron URLs cannot be built. " +
        "Run this where the app's .env is readable.",
    );
  }
  return url.replace(/\/+$/, "");
}

/**
 * Where each run's stderr goes. Overridable, because the default needs root.
 *
 * `curl -fsS` prints nothing on success, so this only grows when something is
 * actually wrong — which is the point: a cron that has been failing silently
 * for a week should leave a week of evidence.
 */
function logPath(): string {
  return process.env.CRON_LOG || "/var/log/flockinsight-cron.log";
}

/**
 * A secret cron cannot carry safely is a refusal, not a warning.
 *
 * `%` in a crontab command field is a newline, and this platform has already
 * lost a job to exactly that. A newline in the value would end the assignment
 * and leave the rest as a command. Both produce a crontab that installs
 * cleanly and then does something other than what it says.
 */
function assertUsableSecret(secret: string) {
  if (/[%\r\n]/.test(secret)) {
    throw new Error(
      "CRON_SECRET contains a % or a newline, which crontab cannot carry " +
        "literally — % becomes a newline in a command. Rotate it to something " +
        "without those characters before installing.",
    );
  }
}

function render(): string {
  const url = baseUrl();
  const log = logPath();
  const secret = process.env.CRON_SECRET ?? "SET_CRON_SECRET_HERE";
  if (process.env.CRON_SECRET) assertUsableSecret(process.env.CRON_SECRET);
  const jobs = Object.keys(CRON_JOBS) as CronJob[];
  const width = Math.max(...jobs.map((j) => CRON_JOBS[j].cron.length));

  const lines = [
    BEGIN,
    "# Generated by scripts/print-crontab.ts from src/lib/cron-schedule.ts.",
    "# Edit the schedule THERE, re-run with --install. Do not hand-edit here.",
    "#",
    "# $CRON_KEY is read from the environment below, so the secret is written",
    "# once rather than on thirteen lines.",
    "#",
    "# AN AUTHORIZATION HEADER, NOT ?key=. The routes accept both, and the",
    "# query-string form is what was in use here — which put CRON_SECRET into",
    "# the Apache access log, Cloudflare's logs and any Referer sent onward,",
    "# on every single run, several times a minute. A header appears in none",
    "# of them. The value is still visible in `ps` to anyone with an account",
    "# on this box, which is the remaining reason to keep shell access to it",
    "# narrow and the secret rotatable.",
    "#",
    "# IF THIS BOX EVER RAN THE ?key= FORM, TREAT CRON_SECRET AS DISCLOSED AND",
    "# ROTATE IT: change it in the app's .env, restart with",
    "# `pm2 restart all --update-env` (without --update-env the old value is",
    "# kept and nothing changes), then re-run this script with --install.",
    "SHELL=/bin/bash",
    `CRON_KEY=${secret}`,
    "",
  ];

  for (const job of jobs) {
    const meta = CRON_JOBS[job];
    lines.push(`# ${meta.label} — every ${human(meta.intervalMinutes)}`);
    lines.push(
      `${meta.cron.padEnd(width)} curl -fsS --max-time 300 ` +
        `-H "Authorization: Bearer $CRON_KEY" ` +
        `"${url}/api/cron/${job}" ` +
        `>> ${log} 2>&1`,
    );
  }

  lines.push("", END);
  return lines.join("\n") + "\n";
}

function human(mins: number): string {
  if (mins % 1440 === 0) return mins === 1440 ? "day" : `${mins / 1440} days`;
  if (mins % 60 === 0) return mins === 60 ? "hour" : `${mins / 60} hours`;
  return `${mins} minutes`;
}

async function install(block: string) {
  const { execFileSync } = await import("node:child_process");
  const fs = await import("node:fs");
  const os = await import("node:os");
  const path = await import("node:path");

  let current = "";
  try {
    current = execFileSync("crontab", ["-l"], { encoding: "utf8" });
  } catch {
    // No crontab yet for this user. An empty one is the right starting point.
    current = "";
  }

  /*
   * Keep a copy before touching anything. The crontab on this box holds
   * backups and a watchdog as well as these jobs, and `crontab -` replaces the
   * whole file — so the one irreversible step gets a backup first.
   *
   * OWNER-ONLY, IN AN OWNER-ONLY DIRECTORY. A crontab holds secrets — this
   * one has carried CRON_SECRET on every line — and the default mode is
   * whatever umask says, which on most boxes is world-readable. The directory
   * is locked down as well as the file, because a mode passed to
   * `writeFileSync` only applies when the file is created, and an explicit
   * `chmod` after the write is what makes that true regardless.
   */
  const dir = path.join(os.homedir(), ".crontab-backups");
  fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  fs.chmodSync(dir, 0o700);
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backup = path.join(dir, `crontab.${stamp}`);
  fs.writeFileSync(backup, current, { encoding: "utf8", mode: 0o600 });
  fs.chmodSync(backup, 0o600);
  console.error(`existing crontab saved to ${backup} (mode 600)`);

  const begin = current.indexOf(BEGIN);
  const end = current.indexOf(END);
  let next: string;
  if (begin !== -1 && end !== -1 && end > begin) {
    next = current.slice(0, begin) + block + current.slice(end + END.length + 1);
  } else {
    /*
     * First install. APPENDED, never substituted for what is already there —
     * the lines already in this crontab are doing work nobody asked us to
     * take over. Any job of ours that happens to be listed separately will now
     * run twice, which is harmless (every route is idempotent) but untidy, so
     * the operator is told to go and remove the old lines by hand.
     */
    next = (current.endsWith("\n") || current === "" ? current : current + "\n") +
      "\n" + block;
    console.error(
      "\nNOTE: this is a first install, so the block was APPENDED. If any of " +
        "these jobs\nalready had their own line in the crontab, they will now " +
        "run twice. Review with\n`crontab -l` and delete the old lines by " +
        "hand — nothing was removed for you.",
    );
  }

  execFileSync("crontab", ["-"], { input: next, encoding: "utf8" });
  console.error("installed. Verify with: crontab -l");
}

async function main() {
  const block = render();
  if (process.argv.includes("--install")) {
    await install(block);
  } else {
    process.stdout.write(block);
  }
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
});
